name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - name: Run Tests
        run: npm test
        if: runner.os != 'Linux'
      - name: Update Version
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: |
          # Extract version from tag (removes 'refs/tags/v' or 'refs/tags/' prefix)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          # Update package.json version
          npm version $VERSION --no-git-tag-version --allow-same-version
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
